git_lfs_enabled: false

backend:
  name: git-gateway
  branch: main

# On spécifie que les fichiers téléversés iront dans un dossier "programmes"
# pour garder le projet propre.
media_folder: "programmes"
public_folder: "/programmes"

collections:
  - name: "programme"
    label: "Programme"
    files:
      - label: "Programme Trimestriel"
        name: "programme_pdf"
        file: "_data/programme.json"
        fields:
          - label: "Mettre à jour le programme (PDF)"
            name: "fichier_pdf"
            widget: "file"
            media_folder: "programmes" # On confirme le dossier d'upload
            public_folder: "/programmes"
