# "Backend" : comment le CMS se connecte à votre projet
backend:
  name: git-gateway
  branch: main # La branche principale de votre projet

# Où stocker les images que les administrateurs téléverseront
media_folder: "image" # Le nom de votre dossier d'images
public_folder: "/image" # Comment accéder à ce dossier depuis le site

# "Collections" : Les types de contenu que vous pouvez modifier
collections:
  - name: "evenements" # Nom technique
    label: "Événements" # Nom affiché dans le CMS
    files:
      - file: "_data/evenements.json"
        label: "Liste de tous les événements"
        name: "liste_evenements"
        widget: "list"
        fields:
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Date et Heure", name: "date", widget: "datetime"}
          - {label: "Lieu", name: "lieu", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "permanences"
    label: "Permanences"
    files:
      - file: "_data/permanences.json"
        label: "Liste de toutes les permanences"
        name: "liste_permanences"
        widget: "list"
        fields:
          - {label: "Jour", name: "jour", widget: "string", hint: "Ex: Lundi, Mardi..."}
          - {label: "Heure", name: "heure", widget: "string", hint: "Ex: 18h00 - 19h30"}
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Lieu", name: "lieu", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
