backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "evenements"
    label: "Événements"
    folder: "_evenements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "titre", widget: "string"}
      - {label: "Date et Heure", name: "date", widget: "datetime"}
      - {label: "Lieu", name: "lieu", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
       # --- LIGNES À AJOUTER CI-DESSOUS ---
      - label: "Tarif"
        name: "tarif"
        widget: "string"
        required: false # Ce champ n'est pas obligatoire
        hint: "Ex: 5€, Gratuit, 10€ pour non-adhérents..."

  - name: "permanences"
    label: "Permanences"
    folder: "_permanences"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "titre", widget: "string"}
      - {label: "Jour de la semaine", name: "jour", widget: "string"}
      - {label: "Heure", name: "heure", widget: "string"}
      - {label: "Lieu", name: "lieu", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
